[package]
name = "core"
version = "2.6.1"
description = "The Motoko standard library"
repository = "https://github.com/caffeinelabs/motoko-core"
keywords = [
  "core",
  "base",
  "data-structure",
  "stable-memory",
  "persistent"
]
license = "Apache-2.0"

[dev-dependencies]
test = "2.1.2"
bench = "2.0.1"
fuzz = "1.0.0"
matchers = "2.1.0"
base-0-14-13 = "https://github.com/dfinity/motoko-base#moc-0.14.13@794174a307975c225cfb26b57f73e38a841c0415"
bench-helper = "0.0.3"

[requirements]
moc = "1.6.0"

[toolchain]
moc = "1.8.0"
wasmtime = "44.0.0"
pocket-ic = "12.0.0"

[moc]
args = ["-E=M0154,M0223"]
